e_datamining<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("## 파일로딩하기 ------- ", '\n')
cat("library(tidyverse) ", '\n')
cat("df<-read.csv(file.choose(), skip=1, header=T, fileEncoding='CP949', encoding='UTF-8') ", '\n')
cat(" ", '\n')
cat("library(readxl) ", '\n')
cat("df<-read_excel(file.choose(), skip=1) ", '\n')
cat(" ", '\n')
cat("## 자료에 NA가 있으면, na.rm=T 사용 -------   ", '\n')
cat("## 일부 변수를 선택해 새데이터셋 만들기 ------- ", '\n')
cat("index <- c(2,4:6) ", '\n')
cat("df2 <- df[ , index] ", '\n')
cat(" ", '\n')
cat("## 데이터셋의 특정 변수 지우기 ------- ", '\n') 
cat("df <- df[ , -c(2, 4:5)] ", '\n')
cat(" ", '\n')
cat("## 자료를 솎아내서 새데이터 만들기 ------- ", '\n')
cat("df2 <- df[ df$debtratio !=Inf , ] ", '\n')
cat("df2 <- df[ !is.na(df$debtratio) , ] ", '\n')
cat("df2 <- df[ df$debtratio <= 124 , ] ", '\n')
cat("df2 <- df[ complete.cases(df$편의성, df$가격만족, df$연령대), ]  ", '\n')
cat(" ", '\n')
cat("## 코드값 재코딩 ------- ", '\n')
cat("library(aj412s) ", '\n')
cat("df$conv2[df$conv==5] <- 4 ", '\n')
cat("df$gender2[df$gender==2] <- 0 ", '\n')
cat("df[df==''] <- NA  ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("## 자료수 확인 ------- ", '\n')
cat("sum(is.na(df$브랜드))  ", '\n')
cat("sum(!is.na(Adata$브랜드))  ", '\n')
cat("sum(Adata$브랜드=='Ford') ", '\n')
cat(" ", '\n')
cat("## 변수명 변경 ------- ", '\n')
cat("colnames(BasicData)<-c('id','brand','conv','satprice','age','gender') ", '\n')
cat("colnames(BasicData)[6]<-c('성별') ", '\n')
cat(" ", '\n')
cat("## 더미변수 만들기 ------- ", '\n')
cat("library(fastDummies)  ", '\n')
cat("df<-data(BasicData) ", '\n')
cat("df<-dummy_cols(df, 'age') ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("## 문자 레코드를 숫자로 바꾸기 -------- ", '\n')
cat("library(aj412s); df<-read_excel('자료1.xlsx') ", '\n')
cat("df$브랜드2<-c2n(df$브랜드) ", '\n')
cat(" ", '\n')
cat("## 여러 개의 변수들을 numeric으로 지정하기 -------- ", '\n')
cat("index <- c(4, 5, 11:23)  ", '\n')
cat("df[,index] <- lapply(df[,index], as.numeric)  ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("## Grouping변수 만들기 ------- ", '\n')
cat("cn<-quantile(df$income, c(.25, .5, .75) , na.rm=T) ", '\n')
cat("df$income2<-mkgroup(df$income, cn) ", '\n')
cat(" ", '\n')
cat("## density그래프 그리기 ------- ", '\n')
cat("ggplot(df, aes(x=income)) + geom_density() ", '\n')
cat(" ", '\n')
cat("## 결과의 저장 ------- ", '\n')
cat("sink('결과저장.csv')  ", '\n')
cat("  ……  ", '\n')
cat("sink()  ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("## dplyr사용법 ------- ", '\n')
cat("df %>% group_by(브랜드)  ", '\n')
cat("      %>% summarize(편의성평균=mean(편의성, na.rm=T), 표준편차=sd(편의성, na.rm=T), 자료수=n())  ", '\n')
cat("df %>% select(브랜드, 편의성) ", '\n')
cat("df %>% filter(변수E==2015 & (변수F=='C' | 변수F=='G') ) ", '\n')
cat("df %>% arrange(연령대) ", '\n')
cat("df <- rename(df, 새변수명=편의성) ", '\n')
cat("merge(data1, data2, by='index') ", '\n')
cat("   %>% merge(data3, by='index') ", '\n')
cat("   %>% merge(data4, by='index') ", '\n')
cat("    ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("## xtabs를 사용해 막대그래프 그리기 ------- ", '\n')
cat("xtabs(~df$성별+df$브랜드)  ", '\n')
cat("barplot(xtabs(~df$성별+df$브랜드), beside=T, horiz=F, ylab='빈도수')  ", '\n')
cat(" ", '\n')
cat("----------------------------------------------------- ", '\n')
cat("## rowSums 및 rowMeans 명령문 -------  ", '\n')
cat("Adata$check<-rowSums(df[, c(3:4)], na.rm=T)  ", '\n')
cat("Adata$check<-rowMeans(df[, c(3:4)], na.rm=T)  ", '\n')
cat(" ", '\n')


invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("## df$시군구 변수에서 용인수지구 단어가 있는 레코드를 솎아내기 --------", '\n')
cat("df%>%filter( grepl('용인수지구' , df$시군구)) ", '\n')
cat(" ", '\n')
cat("## 상현동 아파트들 중 상떼빌 아파트만 솎아내기 -------- ", '\n')
cat("df%>%filter( grepl('상현동', df$시군구) & grepl('상떼빌', df$단지명)) ", '\n')
cat(" ", '\n')
cat("## 계약년월(예: 202404) 변수에서 5번~6번째 월(04)을 솎아내서 month변수로 저장하기 --------", '\n')
cat("df$month <- substring(df$계약년월, 5,6) ", '\n')
cat(" ", '\n')
cat("## 거래금액에 있는 콤마(82,345)를 제거한 후 거래금액(82345)를 numeric으로 지정하기 --------", '\n')
cat("df$거래금액<-gsub(',', '', df$거래금액) ", '\n')
cat("df$거래금액<-as.numeric(df$거래금액) ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("## year, month, 01을 연결해 날짜변수date0 만들기 -------- ", '\n')
cat("df$month2<-sprintf('-%02d', df$month) ", '\n')
cat("df$date0<-paste0(df$year, df$month2, '-01') ", '\n')
cat("df$date0<-as.Date(df$date0) ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("## subset명령문활용 -------- ", '\n')
cat("subset(df, 평형==32, select=c(date0, 평당매매가평균)) ", '\n')
cat(" ", '\n')
cat("## subset으로 32평 및 41평의 평당매매가평균을 하나의 그래프로 그리기 -------- ", '\n')
cat("plot(subset(df, 평형==32, select=c(date0, 평당매매가평균)), type='l', ", '\n')
cat("     col='cornflowerblue', lwd=2, ylim=c(1000, 2800)) ", '\n')
cat("par(new=T) ", '\n')
cat(" ", '\n')
cat("## subset을 이용해 특정 레코드만 솎아내서 회귀분석하기 -------- ", '\n')
cat("Result <- lm(거래금액~전용면적+층, data=df, subset=c(year==2021)  ) ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("Sample의 추출 --------  ", '\n')
cat("국가<-c('미국','중국','일본','독일','영국','인도','프랑스','이탈리아','캐나다','대한민국' ) ", '\n')
cat("국내총생산<-c(22.99, 17.73, 4.93, 4.22, 2.18, 3.17, 2.93, 2.99, 1.99, 1.81) ", '\n')
cat("인구수<-c('3.39','14.25','1.23','0.83','0.67','14.28','0.64','0.58','0.38','0.51') ", '\n')
cat("df<-as.data.frame(cbind(국가, 국내총생산, 인구수)) ", '\n')
cat("df$일인당국내총생산<-NA ", '\n')
cat("index<-c(2:4) ", '\n')
cat("df[ ,index]<-lapply(df[,index], as.numeric) ", '\n')
cat("df$일인당국내총생산<-df$국내총생산/df$인구수 ", '\n')
cat("index2<-sample(nrow(df), 6, replace=F) ", '\n')
cat("SampleData<-df[index2 , ] ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("확률 및 p값 -------- ", '\n')
cat("정규분포 경계값: qnorm(확률)  ", '\n')
cat("정규분포 p값찾기: 1-pnorm(z값)  ", '\n')
cat("t분포 경계값: qt(확률, n-1)  ", '\n')
cat("t분포 p값찾기: 1-pt(t값, n-1)  ", '\n')
cat("카이자승 경계값: qchisq(확률, 자유도)  ", '\n')
cat("카이자승 p값찾기: 1-pchisq(카이자승값, 자유도)  ", '\n')
cat("F분포 경계값: qf(확률, 자유도1, 자유도2)  ", '\n')
cat("F분포 p값찾기: 1-pf(F값, k-1, n-k)  ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("## substring 사용법: 수원시 -> 마지막 문자인 '시'를 area2에 저장 --------", '\n')
cat("## 문자열의 개수를 알려주는 함수: nchar( ) ", '\n')
cat("for(i in 1:n){ ", '\n')
cat("총문자열수<-nchar(df$area1[i]) ", '\n')
cat("df$area2[i] <- substring(df$area1[i], 총문자열수) }  ", '\n')
cat(" ", '\n')
cat("## substring 사용법: 수원시 -> 기초자치단체명 '수원'을 area3에 저장 -------- ", '\n')
cat("df$area3 <- NA ", '\n')
cat("for(i in 1:n){ ", '\n')
cat("총문자열수_마이너스1<- ( nchar(df$area1[i]) - 1 ) ", '\n')
cat("df$area3[i] <- substring(df$area1[i], 1, 총문자열수_마이너스1) } ", '\n')
cat(" ", '\n')

} }

