e_datamining<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("# 패키지 설치하기 	  ", '\n')
cat("  인터넷연결 → Rstudio → Tools → Install Packages... → 패키지명 입력  ", '\n')
cat("# 패키지 로딩하기 	 ", '\n')
cat("library(readxl); library(dplyr); library(aj412s); library(ggplot2) # 패키지 로딩  ", '\n')
cat("library(moonBook); library(ztable); library(jmv); library(gmodels) # 패키지 로딩  ", '\n')
cat("   ", '\n')
cat("# 데이터셋 로딩하기   ", '\n')
cat("# 데이터셋:Adata /행(row)=레코드={이유현,윤창근,권향원 등의 피조사대상} /열(컬럼)=변수={브랜드,편의성,가격만족,연령대,성별} ", '\n')
cat("Adata <- read_excel('자료1.xlsx') # 엑셀파일 로딩하기. 데이터셋명:Adata, 데이터포맷 data.frame ", '\n')
cat("Bdata <- read.csv('자료1.csv') # csv파일 로딩하기. 데이터셋명:Bdata, 데이터포맷 data.frame ", '\n')
cat("   ", '\n')
cat("# 데이터셋 만들기  ", '\n')
cat("data1 <- seq(1, 12, 3) # data1={ 1 , 4 , 7 , 10 }  # 데이터포맷 vector  ", '\n')
cat("data2 <- rep(NA, 3) # data2={NA ,NA ,NA}  # 데이터포맷 vector  ", '\n')
cat("data3 <- matrix( rep(NA, 9), ncol=3 ) # 데이터포맷 matrix ", '\n')
cat("data4 <- matrix( seq(1, 9, 1), ncol=3 , byrow=T)  # 데이터포맷 matrix ", '\n')
cat("data5 <- matrix( seq(1, 12, 1), ncol=2 , byrow=F)  # 데이터포맷 matrix ", '\n')
cat("data6 <- as.data.frame(data5)  # 데이터포맷 변경 matrix -> data.frame ", '\n')
cat("data7 <- as.vector(data5)  # 데이터포맷 변경 matrix -> vector ", '\n')

cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("# 미싱데이터 처리 및 레코드값 변경  ", '\n')
cat("# 데이터셋에서 '가격만족'변수 선택 및 레코드 선택   ", '\n')
cat("head(Adata, 5) # 데이터셋에서 레코드 5개를 출력하라  ", '\n')
cat("Adata$가격만족  # 데이터셋에서 '가격만족'변수 출력  ", '\n')
cat("Adata$[ ,c(3)]  # 데이터셋에서 '가격만족'변수 즉, 3번째 변수 선택  ", '\n')
cat("Adata$가격만족[5]  # '가격만족'변수의 5번째 레코드 출력  ", '\n')
cat("Adata[c(5) , c(3)] # 3번째 변수의 5번째 레코드 출력  ", '\n')
cat("Adata[, c( '가격만족', '성별')]  # 데이터셋에서 '가격만족' 및 '성별'변수 출력  ", '\n')
cat("Adata[, c(3,5)]  # 데이터셋에서 3번째 변수(가격만족) 및 5번째 변수(성별) 출력  ", '\n')
cat("Adata$편의성[is.na(Adata$편의성)] <- -999 # 데이터셋A의 '편의성'변수 값이 미싱데이터이면 -999로 변경  ", '\n')
cat("Adata$편의성[Adata$편의성==5] <- 4  # 데이터셋A의 '편의성'변수 값이 '5<-4'로 변경  ", '\n')
cat("Adata[ ,c(3:5)][is.na(Adata[ ,c(3:5)])] <- -999 # 데이터셋A의 3번~5번 변수 값이 미싱데이터이면 -999로 변경   ", '\n')
cat("Adata$브랜드[is.na(Adata$브랜드)] <- 'McLaren' # 브랜드 값이 미싱데이터면 'McLaren'으로 변경    ", '\n')
cat("Adata$브랜드[Adata$브랜드=='Ford'] <- 'Lotus' # 브랜드 값이 'Ford'면 'Lotus'로 변경    ", '\n')
cat("Adata <- read_excel('자료1.xlsx') # 엑셀파일 재로딩. 새Adata가 구Adata를 덮어쓴다. ", '\n')
cat("Adata <- Adata[complete.cases(Adata$가격만족), ] # '가격만족'변수에 미싱데이터 있으면 레코드 삭제 ", '\n')
cat("Adata <- Adata[complete.cases(Adata), ] # Adata셋 미싱데이터가 있는 레코드 삭제 ", '\n')
cat("  ", '\n')
cat("# 레코드값 변경 연습1  ", '\n')
cat("Bdata <- read_excel('자료2.xlsx', sheet=3, skip=6)  ", '\n')
cat("Bdata$gender[Bdata$gender=='①'] <- 1  # gender 레코드 변경. gender변수의 속성은 문자(character)  ", '\n')
cat("Bdata$gender[Bdata$gender=='②'] <- 2  # gender 레코드 변경  ", '\n')
cat("Bdata$gender <- as.numeric(Bdata$gender)  # gender변수의 속성을 숫자(numeric)로 변경  ", '\n')
cat("Bdata$gender <- as.character(Bdata$gender)  # gender변수의 속성을 문자(character)로 변경  ", '\n')
cat("  ", '\n')
cat("# 레코드값 변경 연습2: FOR문을 사용한 재코딩  ", '\n')
cat("Adata$gender2 <- NA # gender의 재코딩 값을 기록할 변수 지정  ", '\n')
cat("n <- nrow(Adata) # Adata의 자료수를 n에 저장 ", '\n')
cat("for(i in 1:n){  ", '\n') # i는 1부터 n까지 1씩 증가
cat("   if(Adata$gender[i]=='①')  {Adata$gender2[i]<- 1} # gender1의 i번째 레코드가 ①이면 gender2의 i번째 변수에 1을 기록 ", '\n')
cat("   else if(Adata$gender[i]=='②')  {Adata$gender2[i]<- 2} # gender1의 i번째 변수가 ②이면 gender2의 i번째 변수에 2를 기록 ", '\n')
cat("   else {Adata$gender2[i] <- NA # gender1의 i번째 레코드가 앞의 조건을 만족하는 것이 없으면 gender2의 i번째 변수에 NA 기록 ", '\n')
cat("} ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("# aj412s::mkdum()로 더미변수 만들기 	  ", '\n')
cat("library(aj412s) ", '\n')
cat("Adata <- read_excel('자료1.xlsx') # 엑셀파일 로딩하기 ", '\n')
cat("# mkdum()에 사용되는 변수는 모두 numeric포맷(O). character포맷의 변수(X). 브랜드(character)->브랜드2(numeric)변경 ", '\n')
cat("Adata$브랜드2 <- c2n(Adata$브랜드) # 브랜드가 character포맷이므로 numeric으로 변경   ", '\n')
cat("Bdata <- mkdum(Adata$브랜드2) # 더미변수 데이터셋Bdata 만들기   ", '\n')
cat("Adata <- cbind(Adata, Bdata) # 원자료Adata와 더미변수 데이터셋Bdata 합치기    ", '\n')
cat("# Bdata의 더미변수 변수명(V1, V2, V3 ...) 변경은 'dplyr::rename()'을 사용    ", '\n')
cat("    ", '\n')
cat("# ifelse로 더미변수 만들기 	  ", '\n')
cat("Adata$dums <- ifelse(Adata$성별==1, 1, 0),  ", '\n')
cat("Cdata$dums <- mkdum(Adata$성별) ", '\n')
cat("    ", '\n')
cat("# 여러 개의 변수들을 numeric으로 지정하기 ", '\n')
cat("index <- c(4, 5, 11:23)  ", '\n')
cat("Adata[,index] <- lapply(Adata[,index], as.numeric)  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("# dplyr사용법 	 ", '\n')
cat("library(dplyr); library(ztable)  ", '\n')
cat("Adata$index0 <- as.numeric( rownames(Adata) )  # 인덱스 변수를 만든다. 데이터를 원래 순서대로 정렬 시 사용됨 ", '\n')
cat("Bdata <- Adata %>% select(브랜드, 편의성) # Adata에서 2개 변수를 추출해 Bdata로 저장 ", '\n')
cat("Adata <- Adata %>% arrange(연령대) # 연령대 변수를 오름차순으로 정리 ", '\n')
cat("Adata <- Adata %>% arrange(desc(연령대)) # 연령대 변수를 내림차순으로 정리 ", '\n')
cat("    ", '\n')
cat("# index변수를 사용해 3개 데이터셋(데이터프레임) 합치기. 3개 데이터셋에는 index가 공통으로 포함되어 있음  ", '\n')
cat("NewData <- merge(data0, data1, by='index') %>% merge(data2, by='index') %>% merge(data3, by='index') ", '\n')
cat("Adata <- mutate(Adata, 새변수 = 기존 변수들을 조합한 수식)  # 기존변수를 조합해 새변수 만들기  ", '\n')
cat("Adata <- rename(Adata, 새변수명=구변수명) # 변수명 변경 ", '\n')
cat("Adata <- Adata %>% relocate(브랜드, .before=성별) # 변수 위치의 변경 ", '\n')
cat("Adata <- Adata %>% relocate(브랜드, .after=성별) # 변수 위치의 변경 ", '\n')
cat("    ", '\n')
cat("tmp<-Adata %>% group_by(브랜드) %>% summarize(편의성평균=mean(편의성, na.rm=T),표준편차=sd(편의성, na.rm=T), 자료수=n()) ", '\n')
cat("# tmp는 tidyverse팀이 만든 data.frame형태. 일반적인 data.frame형태로 다시 저장한 후, ztable로 결과 보기 ", '\n')
cat("Bdata<-as.data.frame(Bdata)  ", '\n')
cat("# tmp가 viewer에 나타나도록 옵션 조정. viewer결과 → 엑셀 → 아래아한글/MS워드 ", '\n')
cat("options(ztable.type='viewer') ", '\n')
cat("ztable(Bdata) ", '\n')
cat(" ", '\n')
cat("# select=변수추출, filter=레코드추출  ", '\n')
cat("Adata<-select(Adata, 편의성, 가격만족, 성별)  ", '\n')
cat("Bdata<-Adata %>% filter( 가격만족>mean(가격만족) )  ", '\n')
cat("Bdata<-Adata %>% filter(변수E==2015 & (변수F=='C' | 변수F=='G') ) ", '\n')
cat(" ", '\n')
cat("# filter + grepl의 사용예  ", '\n')
cat("Bdata<-Adata %>% filter( grepl('HD' , 브랜드) ) ", '\n')
cat("# APT수지구.xlsx파일의 'Adata$시군구' 변수에서 용인수지구 단어가 있는 레코드를 솎아내기 ", '\n')
cat("Adata %>% filter( grepl('용인수지구' , Adata$시군구)) ", '\n')
cat(" ", '\n')
cat("# 상현동 아파트들 중 상떼빌 아파트만 솎아내기 ", '\n')
cat("Adata %>% filter( grepl('상현동', Adata$시군구) & grepl('상떼빌', Adata$단지명)) ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("# 자료수 및 기초통계  ", '\n')
cat("sum(Adata$브랜드=='Ford') # '브랜드'변수에 'Ford'가 몇 개인지 보여준다 ", '\n')
cat("sum(is.na(Adata$브랜드))  # '브랜드'변수에 미싱데이터가 몇 개인지 보여준다  ", '\n')
cat("sum(!is.na(Adata$브랜드)) # '브랜드'변수에 미싱데이터가 아닌 레코드 갯수가 몇 개인지 보여준다  ", '\n')
cat("# xtabs를 사용해 막대그래프 그리기 ", '\n')
cat("xtabs(~Adata$성별+Adata$브랜드)  ", '\n')
cat("barplot(xtabs(~Adata$성별+Adata$브랜드), beside=T, horiz=F, ylab='빈도수')  ", '\n')
cat("    ", '\n')
cat("# rowSums=행으로 합산 구하기 / rowMeans=행으로 평균 구하기  ", '\n')
cat("Adata$check <- rowSums(Adata[, c(3:4)], na.rm=T)  ", '\n')
cat("Adata$check <- rowMeans(Adata[, c(3:4)], na.rm=T)  ", '\n')
cat("      ", '\n')
cat("# 데이터의 분포 	    ", '\n')
cat("정규분포 경계값: qnorm(확률)  ", '\n')
cat("정규분포 p값찾기: 1-pnorm(z값)  ", '\n')
cat("t분포 경계값: qt(확률, n-1)  ", '\n')
cat("t분포 p값찾기: 1-pt(t값, n-1)  ", '\n')
cat("카이자승 경계값: qchisq(확률, 자유도)  ", '\n')
cat("카이자승 p값찾기: 1-pchisq(카이자승값, 자유도)  ", '\n')
cat("F분포 경계값: qf(확률, 자유도1, 자유도2)  ", '\n')
cat("F분포 p값찾기: 1-pf(F값, k-1, n-k)  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("  ", '\n')
cat("# subset으로 32평 및 41평의 평당매매가평균을 하나의 그래프로 그리기 ", '\n')
cat("Adata <- read_excel('APT수지구.xlsx')  ", '\n')
cat("# 아래 두 줄로 작성한 명령문은 하나의 명령문으로 만들어 실행할 것. 그렇지 않으면 Error발생함  ", '\n')
cat("plot(subset(Adata, 평형==32, select=c(date0, 평당매매가평균)), type='l', ", '\n')
cat("            col='cornflowerblue', lwd=2, ylim=c(1000, 2800)) ", '\n')
cat("  ", '\n')
cat("# 두 개의 그래프를 겹쳐서 그리기 허용  ", '\n')
cat("par(new=T) ", '\n')
cat("  ", '\n')
cat("# 아래 두 줄로 작성한 명령문은 하나의 명령문으로 만들어 실행할 것. 그렇지 않으면 Error발생함  ", '\n')
cat("plot(subset(Cdata, 평형==41, select=c(date0, 평당매매가평균)), type='l', ", '\n')
cat("            col='salmon2', lwd=2, ylim=c(1000, 2800)) ", '\n')
cat("  ", '\n')
cat("# subset을 이용해 특정 레코드만 솎아내서 회귀분석하기 ", '\n')
cat("아무거나 <- lm(거래금액~전용면적+층, data=Adata, subset=(year==2021)  )", '\n')
cat("  ", '\n')
cat("# 원자료에서 Sample 추출하기 	  ", '\n')
cat("국가 <- c('미국','중국','일본','독일','영국','인도','프랑스','이탈리아','캐나다','대한민국' )     ", '\n')
cat("국내총생산 <- c(22.99, 17.73, 4.93, 4.22, 2.18, 3.17, 2.93, 2.99, 1.99, 1.81)     ", '\n')
cat("인구수 <- c('3.39','14.25','1.23','0.83','0.67','14.28','0.64','0.58','0.38','0.51')     ", '\n')
cat("Adata <- as.data.frame(cbind(국가, 국내총생산, 인구수))     ", '\n')
cat("Adata$일인당국내총생산 <- NA     ", '\n')
cat("Adata$일인당국내총생산 <- Adata$국내총생산/Adata$인구수     ", '\n')
cat("index <- c(2:4)    ", '\n')
cat("Adata[,index] <- lapply(Adata[,index], as.numeric) # 국내총생산~일인당국내총생산 변수를 numeric으로 지정  ", '\n')
cat("index2 <- sample(nrow(Adata), 6, replace=F) # replace=T 복원추출(O) /replace=F 복원추출(X)  ", '\n')
cat("SampleData <- Adata[index2 , ]  ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("library(readxl); library(aj412s); Adata<-read_excel('자료1.xlsx') ", '\n')
cat("Adata$브랜드2 <- c2n(Adata$브랜드) # character포맷의 변수를 numeric포맷으로 변경  ", '\n')
cat("  ", '\n')
cat("# 문자열 Datamining 	  ", '\n')
cat("# 수원시 -> 기초자치단체명 '수원'을 area2에 저장 ", '\n')
cat("# 수원시 -> 마지막 문자인 '시'를 area3에 저장 ", '\n')
cat("# nchar( ) = 문자열의 개수를 알려주는 함수 ", '\n')
cat("  ", '\n')
cat("Adata<-read_excel('APT매매경기도.xlsx', skip=15) ", '\n')
cat("Adata$area2 <- NA ", '\n')
cat("Adata$area3 <- NA ", '\n')
cat("for(i in 1:n){ ", '\n')
cat("총문자열수<-nchar(Adata$area1[i]) ", '\n')
cat("for(i in 1:n){ ", '\n')
cat("총문자열수_1마이너스 <- ( nchar(Adata$area1[i]) - 1 ) ", '\n')
cat("Adata$area2[i] <- substring(Adata$area1[i], 1, 총문자열수_1마이너스) } ", '\n')
cat("Adata$area3[i] <- substring(Adata$area1[i], 총문자열수) } #area1의 마지막 문자를 area2에 저장 ", '\n')
cat("  ", '\n')
cat("# 년월일 Date변수 	  ", '\n')
cat("# 계약년월(예: 202301) 변수에서 5번~6번째 월(01)을 솎아내서 month변수로 저장하기 ", '\n')
cat("Adata$month <- substring(Adata$계약년월, 5,6) ", '\n')
cat("  ", '\n')
cat("# year(예:2023), month(예:01), day(01)을 연결해 날짜변수date0 만들기", '\n')
cat("Adata$month2 <- sprintf('-%02d', Adata$month) ", '\n')
cat("Adata$date0 <- paste0(Adata$year, Adata$month2, '-01') ", '\n')
cat("Adata$date0 <- as.Date(Adata$date0) ", '\n')
cat("  ", '\n')
cat("# 콤마제거: 거래금액에 있는 콤마(82,345)를 제거한 후 거래금액(82345)를 numeric으로 지정하기 ", '\n')
cat("Adata$거래금액 <- gsub(',', '', Adata$거래금액) ", '\n')
cat("Adata$거래금액 <- as.numeric(Adata$거래금액) ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("# Data를 엑셀(xlsx)파일로 저장하기 	 ", '\n')
cat("library(moonBook); library(openxlsx) ", '\n')
cat("TempDoc<-mytable(~conv+satprice+gender, data=Adata) ", '\n')
cat("write.xlsx(TempDoc, 'TempDoc.xlsx')  ", '\n')
cat("  ", '\n')
cat("# 화면 스크롤(screen scroll) 저장하기 	  ", '\n')
cat("sink('결과저장.csv')  ", '\n')
cat("  ---- 화면 스크롤 ----  ", '\n')
cat("sink()  ", '\n')

}}
