e_ftest2<-function(explaining=0){
if(explaining==0) {
cat("library(jmv); library(readxl)", '\n')
cat(" ", '\n')
cat("# Two-Way ANOVA ", '\n')
cat("# with(데이터셋, interaction.plot(독립변수1, 독립변수2, 종속변수, fun = mean, main = 'Interaction Plot'))", '\n')
cat("with(Adata, interaction.plot(  gender, circle, involve, fun = mean, main = 'Interaction Plot'))", '\n')
cat(" ", '\n')
cat("Adata<-read.csv('Data1_Exhaust.csv')", '\n')
cat("Adata$gender<-as.factor(Adata$gender)", '\n')
cat("Adata$circle<-as.factor(Adata$circle)", '\n')
cat("jmv::ANOVA(formula = involve ~ gender + circle + gender:circle,  ", '\n')
cat("   data = Adata,  ", '\n')
cat("   effectSize = 'eta',  ", '\n')
cat("   homo = TRUE,  #Levene’s Test를 실행하란 명령문  ", '\n')
cat("   postHoc = ~ gender + circle + gender:circle,  ", '\n')
cat("   postHocCorr='tukey')  # Tukey방법의 PostHoc Test  ", '\n')
cat(" ", '\n')
cat("**** 다른 방법으로 PostHoc Test를 하려면 **** ", '\n')
cat("--- Scheffe방법의 PostHoc Test --- ", '\n')
cat("postHocCorr = 'scheffe' ", '\n')
cat("--- Bonferroni방법의 PostHoc Test --- ", '\n')
cat("postHocCorr = 'bonf'  ", '\n')
cat("--- Holm방법의 PostHoc Test ---", '\n')
cat("postHocCorr = 'holm'  ", '\n')
}}

