e_ggplot<-function(explaining=0){

if(explaining==0) {

cat("  ", '\n')
cat("# --------- 막대그래프 그리기 ------------------- ", '\n')
cat("library(dplyr); library(aj412s); library(readxl); library(ggplot2) ", '\n')
cat("Adata<-read_excel('Data41_Time_Series_data3.xlsx', skip=1) ", '\n')
cat("# Adata의 패키지데이터명: KoreaMacro ------------ ", '\n')
cat("Adata<-KoreaMacro  ", '\n')
cat("  ", '\n')
cat("tmp<-mkdate(Adata$yearmonth) ", '\n')
cat("Adata<-cbind(Adata, tmp) ", '\n')
cat(" ", '\n')
cat("경상수지<-Adata%>%group_by(year)%>%summarize(경상수지평균=mean(surplus)) ", '\n')
cat(" ", '\n')
cat("# 오름차순: ggplot(data=경상수지, aes(x=reorder(year, -경상수지평균), y=경상수지평균)) ... ) ", '\n')
cat("# 내림차순: ggplot(data=경상수지, aes(x=reorder(year, 경상수지평균), y=경상수지평균)) ... ) ", '\n')
cat(" ", '\n')
cat("ggplot(data=경상수지, aes(x=year, y=경상수지평균))  ", '\n')
cat("막대그래프 셋업 + geom_bar(stat='identity', fill='steelblue', col='black')  ", '\n')
cat("막대그래프 위에 값표시 + geom_text( data=경상수지, aes(y=경상수지평균, label = round(경상수지평균,0), vjust=-1, size=4) )  ", '\n')
cat("x축값 표시 + theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5))  ", '\n')
cat("y축값 표시 + theme(axis.text.y=element_text(color='black', size=13))  ", '\n')
cat("y축값 자리수 + scale_y_continuous(labels =scales:: comma) ", '\n')
cat("제목 크기 + theme(title=element_text(size=30, face='bold'))  ", '\n')
cat("x축명크기 + theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("y축명크기 + theme(axis.title.y = element_text(size=25,face='bold'))  ", '\n')
cat("xy축/제목 타이틀 + labs(x='연도', y='경상수지평균', title='연도별 경상수지평균')  ", '\n')
cat("범례제목 삭제 + theme(legend.position = 'none')  ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("  ", '\n')
cat("# ---- 직선 그리기 -------------------- ", '\n')
cat("geom_line(mapping=aes(x=컬럼이름X,  ", '\n')
cat("                        y=컬럼이름Y,  ", '\n')
cat("                        group=컬럼이름K,  ", '\n')
cat("                        linetype=컬럼이름K,  ", '\n')
cat("                        color=컬럼이름K),  ", '\n')
cat("			linewidth=숫자A, ...)  ", '\n')
cat("  ", '\n')
cat("코스피<-Adata%>%group_by(year)%>%summarize(KOSPI평균=mean(kospi))  ", '\n')
cat("  ", '\n')
cat("ggplot(data=코스피, aes(x=year, y=KOSPI평균))  ", '\n')
cat("직선 셋업 + geom_line(group=1, col='red', linewidth=1)  ", '\n')
cat("점 셋업 + geom_point(col='red', size=3.0)  ", '\n')
cat("y값 표시 + geom_text( data=코스피, aes(y=KOSPI평균, label = round(KOSPI평균,0), vjust=-1, size=4) )  ", '\n')
cat("x축값 표시 + theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5))  ", '\n')
cat("y축값 표시 + theme(axis.text.y=element_text(color='black', size=13))  ", '\n')
cat("y축값 자리수 + scale_y_continuous(labels =scales:: comma)  ", '\n')
cat("제목 크기 + theme(title=element_text(size=30, face='bold'))  ", '\n')
cat("y축명크기 + theme(axis.title.y = element_text(size=25,face='bold'))  ", '\n')
cat("x축명크기 + theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("xy축/제목 타이틀 + labs(x='연도', y='연간 코스피평균', title='연도별 코스피평균')  ", '\n')
cat("범례제목 삭제 + theme(legend.position = 'none')  ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("  ", '\n')

cat("# ---- 산포도 그리기I -------------------- ", '\n')
cat("mpg=연비(hwy), cyl=엔진의 기통수, disp=배기량, hp=마력, drat=뒤차축비, wt=무게, ", '\n')
cat("qsec=1/4mile 도달시간, vs=(0:V-엔진/1:Straight-엔진), am=변속기어(0:오토, 1=변속기어) ", '\n')
cat("gear=전진기어 갯수, carb=캬뷰레터(기화기) 갯수 ", '\n')
cat(" ", '\n')
cat("ggplot(데이터A, ", '\n')
cat("		aes=(x=컬럼이름X, ", '\n')
cat("		y=컬럼이름Y))+ ", '\n')
cat("		geom_point()+ geom_smooth() ", '\n')
cat(" ", '\n')
cat("ggplot(data=mpg,mapping = aes(x=displ, y=hwy)) ", '\n')
cat("	+ geom_smooth() ", '\n')
cat("	+ geom_point() ", '\n')
cat(" ", '\n')
cat("mtcars$cyl<-as.factor(mtcars$cyl) ", '\n')
cat("mtcars$gear <- as.factor(mtcars$gear) ", '\n')
cat("ggplot(data = mtcars, aes(x=disp, y=mpg, shape=cyl, col=cyl))  ", '\n')
cat("점 셋업 + geom_point(size=3)  ", '\n')
cat("x축값 표시 + theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5))  ", '\n')
cat("y축값 표시 + theme(axis.text.y=element_text(color='black', size=13))  ", '\n')
cat("y축값 자리수 + scale_y_continuous(labels =scales:: comma)  ", '\n')
cat("제목 크기 + theme(title=element_text(size=30, face='bold'))  ", '\n')
cat("x축명크기 + theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("y축명크기 + theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("xy축/제목 타이틀+ labs(x='자동차 배기량', y='자동차 연비', title='배기량 대비 연비')  ", '\n')
cat("범례타이틀 지정+ scale_colour_discrete(name='엔진의 기통수')  ", '\n')
cat("범례타이틀 지정+ scale_shape_discrete(name='엔진의 기통수')  ", '\n')
cat("범례타이클 크기/범례글자 크리 + theme(legend.title=element_text(size=14), legend.text=element_text(size=10)) ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("  ", '\n')

cat("# ---- 산포도 그리기II -------------------- ", '\n')
cat("ggplot(mtcars) ", '\n')
cat("점 셋업 + geom_point(aes(x=disp, y=mpg, size=2.5))  ", '\n')
cat("선 추가 + geom_smooth(aes(x=disp, y=mpg))  ", '\n')
cat("x축값 표시 + theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5))  ", '\n')
cat("y축값 표시 + theme(axis.text.y=element_text(color='black', size=13))  ", '\n')
cat("y축값 자리수 + scale_y_continuous(labels =scales:: comma)  ", '\n')
cat("제목 크기 + theme(title=element_text(size=30, face='bold'))  ", '\n')
cat("x축명크기 + theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("y축명크기 + theme(axis.title.y = element_text(size=25,face='bold'))  ", '\n')
cat("xy축/제목 타이틀 + labs(x='자동차 배기량', y='자동차 연비', title='배기량 대비 연비')  ", '\n')
cat("범례 삭제 + theme(legend.position = 'none')  ", '\n')


}}