e_plot<-function(explaining=0){
if(explaining==0) {
cat("library(readxl) ", '\n')
cat("------------------------------------------------- ", '\n')
cat("Adata<-read_excel('Data41_Time_series_data3.xlsx', skip=1) ", '\n') 
cat("Adata$yearmonth<-paste0(Adata$yearmonth, '-01') ", '\n')
cat("Adata$yearmonth<-as.Date(Adata$yearmonth, format='%Y-%m-%d') ", '\n')
cat("plot(Adata$yearmonth, Adata$surplus, type='l', col='red', xlab='',ylab='', cex.lab=1.3) ", '\n')
cat("par(new=TRUE) ", '\n')
cat("plot(Adata$yearmonth, Adata$kospi, type='l', col='blue', xlab='',ylab='', axes=FALSE) ", '\n')
cat("axis(side = 4, col = 'blue') ", '\n')
cat("mtext('KOSPI지수', side = 4, col='blue' , cex.lab=1.3) ", '\n')
cat("title(main='경상수지와 코스피지수',xlab='시간',ylab='경상수지', cex.lab=1.3, cex.main=1.3) ", '\n')
cat("------------------------------------------------- ", '\n')
cat("library(readxl) ", '\n')
cat("Adata<-read_excel('Data42_Suwon.xlsx') ", '\n')
cat("colnames(Adata)<-c('date0','index','budget','rev','accrev','exp','accexp','slack') ", '\n')
cat("Adata$date0<-as.Date(Adata$date0) ", '\n')
cat("Adata$accrev<-Adata$accrev/1000000000 ", '\n')
cat("Adata$accexp<-Adata$accexp/1000000000 ", '\n')
cat("Adata$slack<-Adata$slack/1000000000 ", '\n')
cat("plot(x=Adata$date0, y=Adata$accrev, type='l', lwd='3', lty='dotted', col='red', xlab='',ylab='', ylim=c(10, 4000)) ", '\n')
cat("par(new=TRUE) ", '\n')
cat("plot(x=Adata$date0, y=Adata$accexp, type='l', lwd='3', lty='twodash', col='blue', xlab='', ylab='', ylim=c(10, 4000)) ", '\n')
cat("par(new=TRUE) ", '\n')
cat("plot(x=Adata$date0, y=Adata$slack, type='l', lwd='3', lty='solid', col='salmon3', xlab='', ylab='', ylim=c(10, 4000)) ", '\n')
cat("title(main='세입/세출/여유자원  ', xlab='시간', ylab='세입(Red)/세출(Blue)/여유자산(Brown)/단위:10억', cex.main=2, cex.lab=1.2) ", '\n')

}}
